export const CREATE_CONTRACT = 'CREATE_CONTRACT';
export const CREATE_CONTRACT_SUCCESS = 'CREATE_CONTRACT_SUCCESS';
export const UPDATED_DATA_USER = 'UPDATED_DATA_USER';
export const UPDATED_SOCKET = 'UPDATED_SOCKET';
export const CREATE_TRONWEB = 'CREATE_TRONWEB';
